[package]
name = "wruff-bot"
version = "0.1.0"

edition = "2021"

[dependencies]
tracing = { version = "0.1.43" }
tracing-subscriber = "0.3.22"
tokio = { version = "1.48.0", features = ["full"] }
dotenvy = { git = "https://github.com/allan2/dotenvy", branch = "main", features = [
    "macros",
] }
